### ISSUE TITLE
Support for V8 Script engine

### ISSUE THREAD

**Issue by tglman** [bayne/dot-http#47]
Boa script engine is quite cool but is still a lot experimental, so I was thinking if you would like to have in also de support of V8 script engine.

I've been playing a bit with this and I think I can have an implementation of the ScriptEngine with V8 in not too long time, I was thinking to have it behind a feature gate and leaving by default the boa engine.

Would you consider a PR with this?

Regards

**Comment by bayne** [comment]
Absolutely! I've had the same idea before but never put it to paper. I'm definitely interested in a V8 script engine implementation.

My initial concerns with using V8 was possible bloat it might introduce but I've never actually validated this. I would love to see what you got.

**Comment by tglman** [comment]
Hi,
Here is a PR with from my branch with the implementation with the support of v8:  https://github.com/bayne/dot-http/pull/48 any feedbacks are welcome.
Regards
