### ISSUE TITLE
Allow the first line comment generated by IntelliJ

### ISSUE THREAD

**Issue by pointerless** [bayne/dot-http#63]
This project seems awfully similar to the [IntelliJ http client](https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html) however that has the unfortunate property of autogenerating the request separator comment, `###`, on the first line. 

Could this be ignored and skipped over so IntelliJ written http scripts could be executed in this without editing?

Currently the output with the initial separator is:
```
Error: Failed parsing file: "/home/pointerless/.../list-all-data.http"

Caused by:
     --> 1:1
      |
    1 | ###␊
      | ^---
      |
      = expected file
```

**Comment by bayne** [comment]
Yep that was my initial use case, I wanted a tool that was able to use the
format that IntelliJ had.

Could you provide a quick example script and show what is expected vs what
the actual result was?
